# This workflow will build a .NET project.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CICD

on:
  push:
    branches: [ "main" ]

jobs:

  generate-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Github Tag Bump
      id: tag_bump
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.0.2
        DEFAULT_BUMP: patch
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.tag_bump.outputs.new_tag }}
      
  build-deploy:
    runs-on: ubuntu-latest
    needs: generate-version
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Pack
      run: dotnet pack --configuration Release -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} -o packages
    - name: Publish
      run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.NuGetPackagePush }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ needs.generate-version.outputs.new_version }} 
        name: "Inventory.Contracts v${{ needs.generate-version.outputs.new_version }} "
        body: "New release of Inventory.Contracts"
        files: ./packages/*.nupkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
